/**
 * Saved-views API client. Routes through the typed `commands`
 * namespace generated by tauri-specta.
 */

import {
	commands,
	type CreateViewBody as CreateViewBodyBindings,
	type UpdateViewBody as UpdateViewBodyBindings
} from '../bindings';
import type { EntityType } from '../types';
import type { TypeViews, View, ViewKind, ViewsFile } from '../types/view';
import { unwrap } from './client';

export interface CreateViewBody {
	name: string;
	kind?: ViewKind;
	filter?: View['filter'];
	filter_tree?: View['filter_tree'];
	sort_key?: string | null;
	sort_dir?: 'asc' | 'desc';
	group_by_key?: string | null;
	columns?: string[] | null;
	card_properties?: string[] | null;
}

export interface UpdateViewBody {
	name: string;
	kind: ViewKind;
	filter: View['filter'];
	filter_tree?: View['filter_tree'];
	sort_key?: string | null;
	sort_dir?: 'asc' | 'desc';
	group_by_key?: string | null;
	columns?: string[] | null;
	card_properties?: string[] | null;
}

export function getAllViews(): Promise<ViewsFile> {
	return unwrap(commands.coreViewGetAll()) as Promise<ViewsFile>;
}

export function getViewsForType(type: EntityType): Promise<TypeViews> {
	return unwrap(commands.coreViewGetForType(type)) as Promise<TypeViews>;
}

export function createView(
	type: EntityType,
	body: CreateViewBody
): Promise<{ view: View; type_views: TypeViews }> {
	return unwrap(
		commands.coreViewCreate(type, body as unknown as CreateViewBodyBindings)
	) as Promise<{ view: View; type_views: TypeViews }>;
}

export function updateView(
	type: EntityType,
	viewId: string,
	body: UpdateViewBody
): Promise<{ view: View; type_views: TypeViews }> {
	return unwrap(
		commands.coreViewUpdate(type, viewId, body as unknown as UpdateViewBodyBindings)
	) as Promise<{ view: View; type_views: TypeViews }>;
}

export function deleteView(type: EntityType, viewId: string): Promise<TypeViews> {
	return unwrap(commands.coreViewDelete(type, viewId)) as Promise<TypeViews>;
}

export function reorderViews(type: EntityType, ordered_ids: string[]): Promise<TypeViews> {
	return unwrap(commands.coreViewReorder(type, ordered_ids)) as Promise<TypeViews>;
}
