
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async coreBootstrapStatus() : Promise<Result<BootstrapStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("core_bootstrap_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setAppZoom(zoomFactor: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_app_zoom", { zoomFactor }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async copyFile(sourcePath: string, destinationPath: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("copy_file", { sourcePath, destinationPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openPath(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_path", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async readFileBytes(path: string) : Promise<Result<number[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_file_bytes", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Reveal `path` in the OS file manager (Finder/Explorer/Files), with the file
 * selected when the platform supports it.
 */
async revealInFileManager(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reveal_in_file_manager", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List entities of `entity_type`, optionally filtered by tags
 * (intersection semantics). Delegates to vaultdb's `Vault::query`
 * via the `eduport_core::query` adapter — every tag becomes a
 * `Predicate::Contains { field: "tags", ... }` clause, pinned by
 * the `eduport-type/<value>` discriminator. No SQLite cache lookup.
 */
async coreEntityList(entityType: EntityType, tags: string[] | null) : Promise<Result<EntityListItem[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("core_entity_list", { entityType, tags }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List entities whose `parent` frontmatter field equals `parent_file_id`.
 * Cross-type — a Person can be a sub-page of a University, a Note can
 * be a sub-page of an Application, etc. Backs the page-hierarchy
 * "sub-pages" UI in DetailPanel.
 * 
 * Returns a flat list sorted by `name`. The frontend handles the
 * tree shape (this is one fetch per node, lazy on expand).
 */
async coreEntityChildren(parentFileId: string) : Promise<Result<EntityListItem[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("core_entity_children", { parentFileId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Fetch a single entity by `(entity_type, file_id)`. Reads the
 * canonical file via `EntityStore::find_by_name` (same parser as
 * list / reconcile), assembles backlinks from vaultdb's link
 * graph, and emits the full detail payload.
 */
async coreEntityGet(entityType: EntityType, fileId: string) : Promise<Result<EntityDetail, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("core_entity_get", { entityType, fileId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Resolve a wikilink target (e.g. `Stanford`) to a single entity.
 * Errors if the target is ambiguous (matches more than one) or
 * missing. Mirrors the sidecar's `/entities/resolve/{target}`.
 */
async coreEntityResolve(target: string) : Promise<Result<ResolveResult, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("core_entity_resolve", { target }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Create a new entity. The `frontmatter` is an arbitrary JSON
 * object; we serialise it through serde_yaml to match the on-disk
 * YAML and parse it as an `Entity`. The file's body is whatever
 * `body` carries.
 */
async coreEntityCreate(entityType: EntityType, frontmatter: JsonValue, body: string | null) : Promise<Result<CreateResult, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("core_entity_create", { entityType, frontmatter, body }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Update an existing entity (PATCH semantics — the full new
 * frontmatter and body replace the previous ones).
 */
async coreEntityUpdate(entityType: EntityType, fileId: string, frontmatter: JsonValue, body: string | null) : Promise<Result<CreateResult, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("core_entity_update", { entityType, fileId, frontmatter, body }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete an entity. Routes through `EntityStore::delete(.., false)`
 * which moves the file to vaultdb's `.trash/` rather than removing
 * it outright (collision-safe). The trash commands (Phase 9.5)
 * expose list/restore/empty.
 */
async coreEntityDelete(entityType: EntityType, fileId: string) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("core_entity_delete", { entityType, fileId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Return the full schema (all eight types + their properties).
 */
async coreSchemaGet() : Promise<Result<Schema, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("core_schema_get") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Return one entity-type's portion of the schema.
 */
async coreSchemaGetType(entityType: EntityType) : Promise<Result<EntitySchema, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("core_schema_get_type", { entityType }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Add a property to `entity_type`. Triggers a property reindex so
 * the SQL filter surface picks up the new key on existing entities.
 */
async coreSchemaAddProperty(entityType: EntityType, property: JsonValue) : Promise<Result<EntitySchema, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("core_schema_add_property", { entityType, property }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Patch the editable fields of a property. The property's `key`
 * and `type` are immutable post-creation — see
 * `SchemaStore::patch_property` for the full rule set.
 */
async coreSchemaPatchProperty(entityType: EntityType, key: string, patch: PropertyPatch) : Promise<Result<EntitySchema, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("core_schema_patch_property", { entityType, key, patch }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete a property from the schema. Existing entity values for
 * that key become "orphaned" — they remain on disk; the SQL index
 * drops them (so they no longer appear in filter aggregations) but
 * the YAML keeps them until the user runs `purge_orphans`.
 */
async coreSchemaDeleteProperty(entityType: EntityType, key: string) : Promise<Result<EntitySchema, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("core_schema_delete_property", { entityType, key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Reorder the properties of one entity type to match `ordered_keys`.
 * `ordered_keys` must contain exactly the existing keys; otherwise
 * the call errors with `invalid` so the frontend can re-fetch and
 * reconcile UI state.
 */
async coreSchemaReorderProperties(entityType: EntityType, orderedKeys: string[]) : Promise<Result<EntitySchema, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("core_schema_reorder_properties", { entityType, orderedKeys }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Apply the built-in "tier" single-select template to each
 * requested entity type. Idempotent: types that already have a
 * `tier` property are reported with status `exists` rather than
 * erroring.
 */
async coreSchemaApplyTierTemplate(types: EntityType[]) : Promise<Result<TierTemplateResult, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("core_schema_apply_tier_template", { types }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Rewrite every entity of `entity_type` to drop the orphan key
 * `key`. The schema must NOT currently declare this key (refusal
 * is the only safe behaviour — otherwise we'd be silently deleting
 * live values).
 */
async coreSchemaPurgeOrphans(entityType: EntityType, key: string) : Promise<Result<PurgeOrphansResult, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("core_schema_purge_orphans", { entityType, key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async coreViewGetAll() : Promise<Result<ViewsFile, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("core_view_get_all") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async coreViewGetForType(entityType: EntityType) : Promise<Result<TypeViews, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("core_view_get_for_type", { entityType }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async coreViewCreate(entityType: EntityType, body: CreateViewBody) : Promise<Result<ViewMutationResult, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("core_view_create", { entityType, body }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async coreViewUpdate(entityType: EntityType, viewId: string, body: UpdateViewBody) : Promise<Result<ViewMutationResult, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("core_view_update", { entityType, viewId, body }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async coreViewDelete(entityType: EntityType, viewId: string) : Promise<Result<TypeViews, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("core_view_delete", { entityType, viewId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async coreViewReorder(entityType: EntityType, orderedIds: string[]) : Promise<Result<TypeViews, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("core_view_reorder", { entityType, orderedIds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Run an FTS5 query against the index, optionally intersected
 * with a tag filter (intersection semantics — same as the
 * Python sidecar). Empty `q` short-circuits to an empty list to
 * match the frontend's behaviour and avoid a malformed-MATCH
 * error from FTS5 on empty input.
 */
async coreSearch(q: string, limit: number | null, tags: string[] | null) : Promise<Result<SearchHitDto[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("core_search", { q, limit, tags }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Distinct values of `key` over all entities of `entity_type`, with
 * counts. The frontend's property-chip section calls this on mount
 * and on every vault-event refresh.
 * 
 * vaultdb's Predicate AST doesn't have GROUP BY, so we run a
 * type-pinned `Vault::query` and aggregate in-process. The cost is
 * one disk walk (vaultdb's design — no daemon, no cache) + an O(N)
 * pass over the resulting records. For a vault sized like this app
 * targets (thousands of entities at most), that's noise.
 */
async corePropertyValueCounts(entityType: EntityType, key: string) : Promise<Result<PropertyCountsResponse, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("core_property_value_counts", { entityType, key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Filter entities of `entity_type` by the request's text / num /
 * date predicates. Sort and limit handled by vaultdb's `Query`.
 */
async coreFilterEntitiesByProperties(entityType: EntityType, filters: PropertyFiltersRequest) : Promise<Result<EntityListItem[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("core_filter_entities_by_properties", { entityType, filters }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Whole-app health check. Returns counts the frontend uses to show
 * "N entities, M parse errors" in the status bar.
 */
async coreGetStatus() : Promise<Result<AppStatus, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("core_get_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async coreListParseErrors() : Promise<Result<ParseErrorItem[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("core_list_parse_errors") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Counts per entity type. Walks the vault root once and buckets by
 * the `eduport-type/<value>` discriminator tag — one query, no FTS
 * dependency.
 */
async coreGetCounts() : Promise<Result<Partial<{ [key in string]: number }>, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("core_get_counts") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * All user-visible tags across the vault, with counts. Internal
 * discriminator tags (`eduport-type/...` and `eduport-doctype/...`)
 * are suppressed.
 */
async coreGetTags() : Promise<Result<TagCount[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("core_get_tags") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async coreSettingsGet() : Promise<Result<SettingsDto, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("core_settings_get") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Persist new settings and reboot the eduport-core state.
 * 
 * Reboot is unconditional rather than conditional on
 * `data_folder` changing because (a) the user_email is captured
 * inside `EduportState` for EML import discrimination, (b)
 * folder overrides could become reachable later, and (c) the
 * reboot is cheap (drop watcher → open new index → reconcile;
 * sub-second on a vault under our scale targets).
 */
async coreSettingsPut(settings: SettingsDto) : Promise<Result<SettingsDto, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("core_settings_put", { settings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Parse a raw `.eml` byte stream into a structured email body the
 * frontend can preview before deciding to import.
 * 
 * The user_email used for inbound/outbound discrimination comes
 * from `EduportState` (set at boot time from the persisted
 * settings) — not from a per-call argument, so the frontend can't
 * accidentally flip direction.
 */
async coreParseEml(bytes: number[]) : Promise<Result<ParsedEmlDto, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("core_parse_eml", { bytes }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List every `.md` file in the trash directory. `original_path`
 * is inferred from the file's `eduport-type/<value>` tag — when
 * that's missing or unparseable, we fall back to `None` rather
 * than failing the whole listing.
 */
async coreTrashList() : Promise<Result<TrashItem[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("core_trash_list") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Restore a single file from the trash by inferring its original
 * folder from the file's entity-type discriminator.
 */
async coreTrashRestore(body: RestoreBody) : Promise<Result<RestoreResult, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("core_trash_restore", { body }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Permanently delete a single trashed file.
 */
async coreTrashDelete(name: string) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("core_trash_delete", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Permanently empty the trash directory.
 */
async coreTrashEmpty() : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("core_trash_empty") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Toggle a single checkbox line. The frontend sends the 1-based
 * line number it observed; we look up the file via vaultdb (which
 * is the canonical record source — the previous `SELECT path, type
 * FROM entities` SQL queried a column that was dropped when storage
 * moved to the shared vaultdb-fts crate, so the lookup silently
 * returned not_found for every toggle), rewrite the body in place,
 * and refresh the index synchronously.
 */
async coreCheckboxToggle(body: CheckboxToggleBody) : Promise<Result<ToggleResult, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("core_checkbox_toggle", { body }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AppStatus = { 
/**
 * Always `"ok"` today — `&'static str` for zero-alloc; surfaces
 * as `string` over IPC.
 */
status: string; parse_errors: number; entities: number }
export type Backlink = { src_file_id: string; type?: string | null; name?: string | null }
export type BootstrapStatus = { settings_exists: boolean; settings_path: string; 
/**
 * `true` once the eduport-core state has finished its boot
 * reconcile and is ready to serve commands. Lets the frontend
 * distinguish "no settings yet" from "settings exist but the
 * vault is still loading".
 */
core_ready: boolean }
export type CheckboxProperty = { key: string; name: string; description?: string | null; required?: boolean; is_builtin: boolean; default?: boolean | null }
export type CheckboxToggleBody = { file_id: string; line: number; checked: boolean }
export type Combinator = "and" | "or"
/**
 * Stable error envelope returned to the frontend. The `code` is
 * the discriminator; the `message` is human-readable. Keeping
 * these stable across versions is part of the API contract — if
 * you add a code, document it; if you remove one, that's a
 * breaking change.
 */
export type CommandError = { 
/**
 * `#[specta(type = String)]` because the code is a `&'static str`
 * in Rust (zero-alloc constants) but serialises and types as
 * `string` over IPC.
 */
code: string; message: string }
export type CreateResult = { file_id: string }
/**
 * Create-view body. Same shape the frontend's `CreateViewBody`
 * sends. `kind`/`sort_dir` use the same `lowercase` variants the
 * types crate exposes; absent fields take struct defaults.
 */
export type CreateViewBody = { name: string; kind?: ViewKind; filter?: ViewFilter; 
/**
 * Notion-style compound filter (Phase B). `None` keeps the saved
 * view chip-only, exactly like before.
 */
filter_tree?: FilterTree | null; sort_key: string | null; sort_dir?: SortDir; group_by_key: string | null; columns: string[] | null; card_properties: string[] | null }
export type DateProperty = { key: string; name: string; description?: string | null; required?: boolean; is_builtin: boolean; 
/**
 * ISO date string `YYYY-MM-DD`. Validated at use sites; we keep
 * the on-the-wire shape as a String to match Python's behaviour.
 */
default?: string | null }
export type EntityDetail = { file_id: string; type: string; path: string; 
/**
 * Full frontmatter as a serde_json `Value` so the frontend gets
 * the typed entity with its custom-property tail. Same shape
 * the sidecar's GET /entities/{type}/{file_id} returned.
 */
entity: JsonValue; body: string; backlinks: Backlink[] }
/**
 * One row in the entity-list view. Field-for-field compatible with
 * the frontend's `EntityListItem`.
 */
export type EntityListItem = { file_id: string; type: string; name: string; path: string }
/**
 * A single entity type's collection of user-declared properties.
 * Property keys must be unique within this collection.
 */
export type EntitySchema = { properties?: Property[] }
/**
 * Eduport's eight first-class entity types. Stored in record frontmatter
 * as a `eduport-type/<value>` tag (e.g. `eduport-type/university`).
 */
export type EntityType = "university" | "lab" | "person" | "program" | "application" | "document" | "email" | "note"
export type FilterCondition = { property_key: string; operator: FilterOperator; 
/**
 * `None` for unary operators (`IsEmpty`, `IsNotEmpty`).
 */
value?: FilterValue | null }
export type FilterGroup = { op: Combinator; children: FilterNode[] }
/**
 * Either a group (combinator + children) or a leaf condition. The
 * recursive shape supports arbitrary nesting; the Phase-B UI only
 * produces single-group trees.
 */
export type FilterNode = ({ kind: "group" } & FilterGroup) | ({ kind: "cond" } & FilterCondition)
/**
 * Cross-property-type operator catalogue. Not every operator is
 * valid for every property type — the frontend's operator-menu
 * enforces that, and an invalid combo produced by hand-edited YAML
 * is silently ignored by the translator (the predicate just won't
 * match anything).
 */
export type FilterOperator = "equals" | "not_equals" | "is_empty" | "is_not_empty" | "contains" | "not_contains" | "starts_with" | "ends_with" | "gt" | "gte" | "lt" | "lte" | "contains_any" | "does_not_contain"
/**
 * Top-level filter shape. `None` = no filter (matches everything
 * after the type-tag pin).
 */
export type FilterTree = { root: FilterNode | null }
/**
 * Side-channel typed value. Mirrors the operator-vs-value contract
 * in vaultdb's `Predicate::*` shapes.
 */
export type FilterValue = string | number | boolean | 
/**
 * For `ContainsAny` / `DoesNotContain` — a multi-value match.
 */
string[]
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
export type MultiSelectProperty = { key: string; name: string; description?: string | null; required?: boolean; is_builtin: boolean; options?: SelectOption[]; default?: string[] | null }
export type NumberProperty = { key: string; name: string; description?: string | null; required?: boolean; is_builtin: boolean; unit?: string | null; default?: number | null }
/**
 * Restricted set of UI tints for select-option chips. Keep this list in
 * sync with the frontend's option-colour palette.
 */
export type OptionColor = "gray" | "red" | "orange" | "yellow" | "green" | "teal" | "blue" | "purple" | "pink"
export type ParseErrorItem = { path: string; message: string; occurred_at: string }
export type ParsedEmlDto = { from: string; to: string[]; cc: string[]; bcc: string[]; subject: string; date: string | null; body: string; 
/**
 * `"inbound"` or `"outbound"`, matching the frontend's
 * `ParsedEml.direction`. Stored as `&'static str` for zero-alloc;
 * surfaces as `string` over IPC.
 */
direction: string }
/**
 * A user-declared property on an entity type. Tagged enum: the `type`
 * field on the YAML side picks which variant to deserialise.
 */
export type Property = ({ type: "text" } & TextProperty) | ({ type: "number" } & NumberProperty) | ({ type: "date" } & DateProperty) | ({ type: "checkbox" } & CheckboxProperty) | ({ type: "single-select" } & SingleSelectProperty) | ({ type: "multi-select" } & MultiSelectProperty) | ({ type: "url" } & UrlProperty) | ({ type: "relation" } & RelationProperty)
/**
 * One entry in a property-value-count aggregation. Field-for-field
 * compatible with the frontend's `PropertyCount`.
 */
export type PropertyCount = { type: string; value: string; count: number }
export type PropertyCountsResponse = { entity_type: EntityType; key: string; values: PropertyCount[] }
/**
 * Frontend-shaped property filter request. Mirrors what
 * `frontend/src/lib/api/schema.ts:filterEntitiesByProperties`
 * builds. Each map keys a property by name; ranges are
 * `(low, high)` tuples with optional ends.
 */
export type PropertyFiltersRequest = { text?: Partial<{ [key in string]: string }>; num?: Partial<{ [key in string]: [number | null, number | null] }>; date?: Partial<{ [key in string]: [string | null, string | null] }>; 
/**
 * Optional Notion-style compound filter tree (Phase B). Merged
 * with the flat chip filter via AND in the query adapter.
 */
tree?: FilterTree | null; sort: string | null; 
/**
 * `"asc"` or `"desc"`; anything else is treated as ascending.
 */
sort_dir?: string | null }
/**
 * Patch shape sent by the frontend's `patchProperty`. We accept
 * every known field; absent fields mean "leave alone".
 */
export type PropertyPatch = { name: string | null; 
/**
 * Wrapped option so we can express both "leave alone" (None)
 * and "clear the description" (Some(None)).
 */
description?: string | null; required: boolean | null; 
/**
 * Same double-option treatment for nullable unit.
 */
unit?: string | null; options: SelectOption[] | null; 
/**
 * `target_types: null` means "clear", `target_types: [...]`
 * means "set"; absence means "leave alone".
 */
target_types?: EntityType[] | null }
export type PurgeOrphansResult = { rewritten: number; skipped: PurgeSkip[] }
export type PurgeSkip = { file_id: string; reason: string }
export type RelationProperty = { key: string; name: string; description?: string | null; required?: boolean; is_builtin: boolean; 
/**
 * `None` (or absent) means any entity type is permitted as the target.
 * An empty list is rejected — use `None` instead.
 */
target_types?: EntityType[] | null; 
/**
 * Default reference, in `[[target]]` wikilink form.
 */
default?: string | null }
export type ResolveResult = { file_id: string; type: string; name: string }
export type RestoreBody = { name: string }
export type RestoreResult = { path: string; file_id: string }
/**
 * The full user-managed schema. Every [`EntityType`] must have an
 * entry — [`empty_schema`] seeds with all eight types and no
 * properties.
 */
export type Schema = { version?: number; types: Partial<{ [key in EntityType]: EntitySchema }> }
/**
 * Search hit DTO. Same field set as the Python sidecar's response,
 * with `type` instead of Rust's reserved `entity_type` so the
 * frontend's existing parser doesn't need a rename.
 */
export type SearchHitDto = { file_id: string; type: string; name: string; snippet: string }
/**
 * One option in a single-select / multi-select property's option list.
 */
export type SelectOption = { value: string; label: string; color?: OptionColor }
/**
 * Frontend-shaped settings DTO. The frontend uses string types
 * for everything (it doesn't know `PathBuf`), so we accept/return
 * strings here and convert at the boundary.
 */
export type SettingsDto = { data_folder: string; attachments_folder: string; notes_folder: string; theme: string; user_email: string; zoom_factor: number; obsidian_vault?: string | null; confirm_deletes: boolean }
export type SingleSelectProperty = { key: string; name: string; description?: string | null; required?: boolean; is_builtin: boolean; options?: SelectOption[]; default?: string | null }
export type SortDir = "asc" | "desc"
export type TagCount = { tag: string; count: number }
export type TextProperty = { key: string; name: string; description?: string | null; required?: boolean; is_builtin: boolean; default?: string | null }
export type TierStatus = { status: string }
export type TierTemplateResult = { results: Partial<{ [key in string]: TierStatus }>; schema: Schema }
export type ToggleResult = { ok: boolean }
export type TrashItem = { name: string; path: string; original_path: string | null; size: number; modified: string | null }
export type TypeViews = { views?: View[] }
export type UpdateViewBody = { name: string; kind: ViewKind; filter: ViewFilter; filter_tree?: FilterTree | null; sort_key: string | null; sort_dir?: SortDir; group_by_key: string | null; columns: string[] | null; card_properties: string[] | null }
export type UrlProperty = { key: string; name: string; description?: string | null; required?: boolean; is_builtin: boolean; default?: string | null }
export type View = { id: string; name: string; kind?: ViewKind; 
/**
 * Legacy flat filter (text equality / num range / date range).
 * Kept on disk for back-compat; new views can leave this empty
 * and use [`Self::filter_tree`] instead. The two are merged with
 * AND when both are populated — useful for evolving an existing
 * view by *adding* compound conditions without losing the old
 * chip filter.
 */
filter?: ViewFilter; 
/**
 * Notion-style compound filter (AND/OR groups + per-property
 * operators). When present, takes precedence over / merges with
 * `filter`.
 */
filter_tree?: FilterTree | null; sort_key?: string | null; sort_dir?: SortDir; group_by_key?: string | null; 
/**
 * Table view: which property keys to render as columns.
 * `None` → use a sensible default.
 */
columns?: string[] | null; 
/**
 * Board view: which property keys to render on each card.
 */
card_properties?: string[] | null }
/**
 * Frontend-shaped property filter — mirrors the request body of the
 * (legacy) `/api/properties/filter` endpoint.
 */
export type ViewFilter = { text: Partial<{ [key in string]: string }>; 
/**
 * Numeric range: `(min, max)` — either side optional.
 */
num: Partial<{ [key in string]: [number | null, number | null] }>; 
/**
 * Date range as ISO `YYYY-MM-DD` strings — either side optional.
 */
date: Partial<{ [key in string]: [string | null, string | null] }> }
export type ViewKind = "list" | "table" | "board"
export type ViewMutationResult = { view: View; type_views: TypeViews }
export type ViewsFile = { version?: number; types: Partial<{ [key in EntityType]: TypeViews }> }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
